name: example_with_flavors
description: A new Flutter project using legacy per-flavor flutter_launcher_icons-<flavor>.yaml files.
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons_flavors:
    path: ../..

flutter:
  uses-material-design: true
