// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_launcher_icons_flavors/test/abs/icon_generator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:flutter_launcher_icons_flavors/abs/icon_generator.dart' as _i4;
import 'package:flutter_launcher_icons_flavors/config/config.dart' as _i5;
import 'package:flutter_launcher_icons_flavors/config/partial_config.dart'
    as _i3;
import 'package:flutter_launcher_icons_flavors/config/platform_toggle.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePlatformToggle_0 extends _i1.SmartFake
    implements _i2.PlatformToggle {
  _FakePlatformToggle_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePartialConfig_1 extends _i1.SmartFake implements _i3.PartialConfig {
  _FakePartialConfig_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIconGeneratorContext_2 extends _i1.SmartFake
    implements _i4.IconGeneratorContext {
  _FakeIconGeneratorContext_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Config].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfig extends _i1.Mock implements _i5.Config {
  MockConfig() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PlatformToggle get android =>
      (super.noSuchMethod(
            Invocation.getter(#android),
            returnValue: _FakePlatformToggle_0(
              this,
              Invocation.getter(#android),
            ),
          )
          as _i2.PlatformToggle);

  @override
  _i2.PlatformToggle get ios =>
      (super.noSuchMethod(
            Invocation.getter(#ios),
            returnValue: _FakePlatformToggle_0(this, Invocation.getter(#ios)),
          )
          as _i2.PlatformToggle);

  @override
  int get adaptiveIconForegroundInset =>
      (super.noSuchMethod(
            Invocation.getter(#adaptiveIconForegroundInset),
            returnValue: 0,
          )
          as int);

  @override
  bool get removeAlphaIOS =>
      (super.noSuchMethod(
            Invocation.getter(#removeAlphaIOS),
            returnValue: false,
          )
          as bool);

  @override
  bool get desaturateTintedToGrayscaleIOS =>
      (super.noSuchMethod(
            Invocation.getter(#desaturateTintedToGrayscaleIOS),
            returnValue: false,
          )
          as bool);

  @override
  String get backgroundColorIOS =>
      (super.noSuchMethod(
            Invocation.getter(#backgroundColorIOS),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#backgroundColorIOS),
            ),
          )
          as String);

  @override
  bool get hasAndroidAdaptiveConfig =>
      (super.noSuchMethod(
            Invocation.getter(#hasAndroidAdaptiveConfig),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasAndroidAdaptiveMonochromeConfig =>
      (super.noSuchMethod(
            Invocation.getter(#hasAndroidAdaptiveMonochromeConfig),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasPlatformConfig =>
      (super.noSuchMethod(
            Invocation.getter(#hasPlatformConfig),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasWebConfig =>
      (super.noSuchMethod(Invocation.getter(#hasWebConfig), returnValue: false)
          as bool);

  @override
  bool get hasWindowsConfig =>
      (super.noSuchMethod(
            Invocation.getter(#hasWindowsConfig),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasMacOSConfig =>
      (super.noSuchMethod(
            Invocation.getter(#hasMacOSConfig),
            returnValue: false,
          )
          as bool);

  @override
  bool get isCustomAndroidFile =>
      (super.noSuchMethod(
            Invocation.getter(#isCustomAndroidFile),
            returnValue: false,
          )
          as bool);

  @override
  String get androidIconName =>
      (super.noSuchMethod(
            Invocation.getter(#androidIconName),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#androidIconName),
            ),
          )
          as String);

  @override
  String get iosIconName =>
      (super.noSuchMethod(
            Invocation.getter(#iosIconName),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#iosIconName),
            ),
          )
          as String);

  @override
  bool get isCustomIOSFile =>
      (super.noSuchMethod(
            Invocation.getter(#isCustomIOSFile),
            returnValue: false,
          )
          as bool);

  @override
  bool get isNeedingNewAndroidIcon =>
      (super.noSuchMethod(
            Invocation.getter(#isNeedingNewAndroidIcon),
            returnValue: false,
          )
          as bool);

  @override
  bool get isNeedingNewIOSIcon =>
      (super.noSuchMethod(
            Invocation.getter(#isNeedingNewIOSIcon),
            returnValue: false,
          )
          as bool);

  @override
  _i3.PartialConfig toPartial() =>
      (super.noSuchMethod(
            Invocation.method(#toPartial, []),
            returnValue: _FakePartialConfig_1(
              this,
              Invocation.method(#toPartial, []),
            ),
          )
          as _i3.PartialConfig);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [IconGenerator].
///
/// See the documentation for Mockito's code generation for more information.
class MockIconGenerator extends _i1.Mock implements _i4.IconGenerator {
  MockIconGenerator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.IconGeneratorContext get context =>
      (super.noSuchMethod(
            Invocation.getter(#context),
            returnValue: _FakeIconGeneratorContext_2(
              this,
              Invocation.getter(#context),
            ),
          )
          as _i4.IconGeneratorContext);

  @override
  String get platformName =>
      (super.noSuchMethod(
            Invocation.getter(#platformName),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#platformName),
            ),
          )
          as String);

  @override
  _i7.Future<void> createIcons() =>
      (super.noSuchMethod(
            Invocation.method(#createIcons, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  bool validateRequirements() =>
      (super.noSuchMethod(
            Invocation.method(#validateRequirements, []),
            returnValue: false,
          )
          as bool);
}
