import 'dart:convert';
import 'dart:io';

import 'package:image/image.dart';
import 'package:path/path.dart' as path;
import 'package:yaml/yaml.dart';

import '../abs/icon_generator.dart';
import '../constants.dart' as constants;
import '../custom_exceptions.dart';
import '../utils.dart' as utils;
import 'web_template.dart';

/// Renders the `<!--FLI-->…<!--FLIEND-->` block injected into
/// `web/index.html` so that the generated PWA icons are referenced.
// ignore: public_member_api_docs
String metaTagsTemplate(
  String appleMobileWebAppTitle,
  String appleMobileWebAppStatusBarStyle, {
  bool shouldInsertFLIString = false,
}) =>
    '''
  <!--Generated by Flutter Launcher Icons-->
  <!--FLI-->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="$appleMobileWebAppStatusBarStyle">
  <meta name="apple-mobile-web-app-title" content="$appleMobileWebAppTitle">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="icon" type="image/png" href="favicon.png"/>

  <link rel="manifest" href="manifest.json">
  <!--FLIEND-->
  <!--Generated by Flutter Launcher Icons--END-->
''';

/// Generates Web icons for flutter
class WebIconGenerator extends IconGenerator {
  static const _webIconSizeTemplates = <WebIconTemplate>[
    WebIconTemplate(size: 192),
    WebIconTemplate(size: 512),
    WebIconTemplate(size: 192, maskable: true),
    WebIconTemplate(size: 512, maskable: true),
  ];

  /// Creates an instance of [WebIconGenerator].
  ///
  ///
  WebIconGenerator(IconGeneratorContext context) : super(context, 'Web');

  @override
  Future<void> createIcons() async {
    final imagePath = context.webConfig?.imagePath ?? context.config.imagePath;
    if (imagePath == null) {
      throw const InvalidConfigException(constants.errorMissingImagePath);
    }
    final imgFilePath = path.join(context.prefixPath, imagePath);

    context.logger.verbose(
      'Decoding and loading image file at $imgFilePath...',
    );
    final imgFile = await utils.decodeImageFile(imgFilePath);

    // generate favicon in web/favicon.png
    context.logger.verbose('Generating favicon from $imgFilePath...');
    await _generateFavicon(imgFile);

    // generate icons in web/icons/
    context.logger.verbose('Generating icons from $imgFilePath...');
    await _generateIcons(imgFile);

    // update manifest.json in web/manifest.json
    context.logger.verbose(
      'Updating ${path.join(context.prefixPath, constants.webManifestFilePath)}...',
    );
    await _updateManifestFile();

    // inject PWA meta tags into web/index.html
    context.logger.verbose(
      'Updating ${path.join(context.prefixPath, constants.webIndexFilePath)}...',
    );
    await _updateIndexFile();
  }

  @override
  bool validateRequirements() {
    // check if web config exists
    context.logger.verbose('Checking webconfig...');
    final webConfig = context.webConfig;
    if (webConfig == null || !webConfig.generate) {
      context.logger.verbose(
        'Web config is not provided or generate is false. Skipped...',
      );
      return false;
    }
    final resolvedImagePath = webConfig.imagePath ?? context.config.imagePath;
    if (resolvedImagePath == null) {
      context.logger.verbose(
        'Invalid config. Either provide web.imagePath or imagePath',
      );
      return false;
    }

    final imageFullPath = path.join(context.prefixPath, resolvedImagePath);
    if (!File(imageFullPath).existsSync()) {
      context.logger.error('image_path "$imageFullPath" does not exist.');
      return false;
    }

    // verify web platform related files and directories exists
    final entitiesToCheck = [
      path.join(context.prefixPath, constants.webDirPath),
      path.join(context.prefixPath, constants.webManifestFilePath),
      path.join(context.prefixPath, constants.webIndexFilePath),
    ];

    // web platform related files must exist to continue
    final failedEntityPath = utils.areFSEntitiesExist(entitiesToCheck);
    if (failedEntityPath != null) {
      context.logger.error(
        '$failedEntityPath this file or folder is required to generate web icons',
      );
      return false;
    }

    return true;
  }

  Future<void> _generateFavicon(Image image) async {
    final favIcon = utils.createResizedImage(constants.kFaviconSize, image);
    final favIconFile = await utils.createFileIfNotExist(
      path.join(context.prefixPath, constants.webFaviconFilePath),
    );
    await favIconFile.writeAsBytes(encodePng(favIcon));
  }

  Future<void> _generateIcons(Image image) async {
    final iconsDir = await utils.createDirIfNotExist(
      path.join(context.prefixPath, constants.webIconsDirPath),
    );
    // generate icons
    for (final template in _webIconSizeTemplates) {
      final resizedImg = utils.createResizedImage(template.size, image);
      final iconFile = await utils.createFileIfNotExist(
        path.join(iconsDir.path, template.iconFile),
      );
      await iconFile.writeAsBytes(encodePng(resizedImg));
    }
  }

  Future<void> _updateManifestFile() async {
    final manifestFile = await utils.createFileIfNotExist(
      path.join(context.prefixPath, constants.webManifestFilePath),
    );
    final manifestConfig =
        jsonDecode(await manifestFile.readAsString()) as Map<String, dynamic>;

    // update background_color
    if (context.webConfig?.backgroundColor != null) {
      manifestConfig['background_color'] = context.webConfig?.backgroundColor;
    }

    // update theme_color
    if (context.webConfig?.themeColor != null) {
      manifestConfig['theme_color'] = context.webConfig?.themeColor;
    }

    // replace existing icons to eliminate conflicts
    manifestConfig
      ..remove('icons')
      ..['icons'] = _webIconSizeTemplates
          .map<Map<String, dynamic>>((e) => e.iconManifest)
          .toList();

    await manifestFile.writeAsString(utils.prettifyJsonEncode(manifestConfig));
  }

  /// Injects (or refreshes) the PWA meta-tag block in `web/index.html`
  /// between the `<!--FLI-->` and `<!--FLIEND-->` markers.
  ///
  /// If the markers are absent the block is appended once before `</head>`
  /// when a `<head>` is present; otherwise the file is left untouched and
  /// a warning is logged so the user can paste the snippet manually.
  Future<void> _updateIndexFile() async {
    final indexPath = path.join(context.prefixPath, constants.webIndexFilePath);
    final indexFile = File(indexPath);
    if (!indexFile.existsSync()) {
      context.logger.verbose(
        '$indexPath missing; skipping meta-tag injection.',
      );
      return;
    }

    final title = _resolveAppTitle();
    final statusBarStyle = context.webConfig?.themeColor != null
        ? 'black'
        : 'default';
    final block = metaTagsTemplate(title, statusBarStyle);

    var contents = indexFile.readAsStringSync();
    final markerRegex = RegExp(
      r'\s*<!--Generated by Flutter Launcher Icons-->[\s\S]*?<!--Generated by Flutter Launcher Icons--END-->',
    );
    if (markerRegex.hasMatch(contents)) {
      contents = contents.replaceFirst(markerRegex, '\n$block');
    } else {
      final headClose = RegExp(r'</head>', caseSensitive: false);
      if (!headClose.hasMatch(contents)) {
        context.logger.warn(
          '$indexPath has no <head> and no <!--FLI--> markers; '
          'add the following block manually:\n$block',
        );
        return;
      }
      contents = contents.replaceFirstMapped(
        headClose,
        (m) => '$block${m.group(0)}',
      );
    }
    indexFile.writeAsStringSync(contents);
  }

  String _resolveAppTitle() {
    // WebConfig has no title field — fall back to the project pubspec
    // `name`, which is what Flutter's default index.html uses too.
    try {
      final pubspec = File(
        path.join(context.prefixPath, constants.pubspecFilePath),
      );
      if (pubspec.existsSync()) {
        final doc = loadYaml(pubspec.readAsStringSync());
        if (doc is YamlMap && doc['name'] is String) {
          return doc['name'] as String;
        }
      }
    } catch (_) {
      // fall through to empty title
    }
    return '';
  }
}
