import 'dart:convert';
import 'dart:io';

import 'package:image/image.dart';
import 'package:path/path.dart' as path;
import 'package:yaml/yaml.dart';

import '../abs/icon_generator.dart';
import '../constants.dart' as constants;
import '../custom_exceptions.dart';
import '../utils.dart' as utils;
import 'web_template.dart';

/// Renders the `<!--FLI-->…<!--FLIEND-->` block injected into
/// `web/index.html` so that the generated PWA icons are referenced.
// ignore: public_member_api_docs
String metaTagsTemplate(
  String appleMobileWebAppTitle,
  String appleMobileWebAppStatusBarStyle, {
  bool shouldInsertFLIString = false,
}) =>
    '''
  <!--Generated by Flutter Launcher Icons-->
  <!--FLI-->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="$appleMobileWebAppStatusBarStyle">
  <meta name="apple-mobile-web-app-title" content="$appleMobileWebAppTitle">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="icon" type="image/png" href="favicon.png"/>

  <link rel="manifest" href="manifest.json">
  <!--FLIEND-->
  <!--Generated by Flutter Launcher Icons--END-->
''';

/// Generates Web icons for flutter
class WebIconGenerator extends IconGenerator {
  static const _webIconSizeTemplates = <WebIconTemplate>[
    WebIconTemplate(size: 192),
    WebIconTemplate(size: 512),
    WebIconTemplate(size: 192, maskable: true),
    WebIconTemplate(size: 512, maskable: true),
  ];

  /// Creates an instance of [WebIconGenerator].
  ///
  ///
  WebIconGenerator(IconGeneratorContext context) : super(context, 'Web');

  @override
  bool get isOptedIn => context.webConfig?.generate ?? false;

  /// Resolved web output directory honoring (in order):
  /// 1. `web.output_path` (per-flavor explicit override),
  /// 2. `web_<flavor>/` when a flavor is active AND the directory already
  ///    exists in the project (so legacy single-`web/` projects keep
  ///    working until the user opts in by creating the dir),
  /// 3. plain `web/` (legacy default).
  /// Upstream #426.
  String get _resolvedWebDir {
    final explicit = context.webConfig?.outputPath;
    if (explicit != null && explicit.isNotEmpty) return explicit;
    final flavor = context.flavor;
    if (flavor != null && flavor.isNotEmpty) {
      final candidate = 'web_$flavor';
      if (Directory(path.join(context.prefixPath, candidate)).existsSync()) {
        return candidate;
      }
    }
    return constants.webDirPath;
  }

  String get _resolvedFaviconPath => path.join(_resolvedWebDir, 'favicon.png');
  String get _resolvedFaviconIcoPath =>
      path.join(_resolvedWebDir, 'favicon.ico');
  String get _resolvedIconsDir => path.join(_resolvedWebDir, 'icons');
  String get _resolvedManifestPath =>
      path.join(_resolvedWebDir, 'manifest.json');
  String get _resolvedIndexPath => path.join(_resolvedWebDir, 'index.html');

  @override
  Future<void> createIcons() async {
    final webConfig = context.webConfig!;
    final imagePath = webConfig.imagePath ?? context.config.imagePath;
    if (imagePath == null) {
      throw const InvalidConfigException(constants.errorMissingImagePath);
    }
    final imgFilePath = path.join(context.prefixPath, imagePath);

    context.logger.verbose(
      'Decoding and loading image file at $imgFilePath...',
    );
    var imgFile = await utils.decodeImageFile(imgFilePath);

    // Resolve the favicon source — `web.favicon_path` (per #515/#635) wins
    // over `web.image_path` and the top-level. Lets users supply a tight
    // low-padding source for the small favicon while PWA icons keep their
    // safe-zone padding.
    Image faviconSource = imgFile;
    if (webConfig.faviconPath != null && webConfig.faviconPath!.isNotEmpty) {
      faviconSource = await utils.decodeImageFile(
        path.join(context.prefixPath, webConfig.faviconPath!),
      );
    }

    // Letter-box non-square sources so every generated icon size preserves
    // aspect ratio (upstream #214). Color resolution: `web.background_color`
    // (explicit per-platform) → top-level `background_color` (generic
    // default). No-op when both are unset — legacy squish behavior is kept
    // for backward compatibility.
    final webBgHex =
        webConfig.backgroundColor ?? context.config.backgroundColor;
    if (webBgHex != null) {
      final bg = utils.parseHexColor(webBgHex);
      imgFile = utils.letterBoxToSquare(imgFile, bg);
      faviconSource = utils.letterBoxToSquare(faviconSource, bg);
    }

    // generate favicon.png (always, when web is enabled)
    context.logger.verbose('Generating favicon.png from $imgFilePath...');
    await _generateFavicon(faviconSource);

    // generate favicon.ico when enabled (upstream #540 / #152)
    if (webConfig.generateFavicon) {
      context.logger.verbose(
        'Generating multi-size favicon.ico from $imgFilePath...',
      );
      await _generateFaviconIco(faviconSource);
    }

    // generate icons in web/icons/
    context.logger.verbose('Generating icons from $imgFilePath...');
    await _generateIcons(imgFile);

    // update manifest.json in <web-dir>/manifest.json
    context.logger.verbose(
      'Updating ${path.join(context.prefixPath, _resolvedManifestPath)}...',
    );
    await _updateManifestFile();

    // inject PWA meta tags into <web-dir>/index.html
    context.logger.verbose(
      'Updating ${path.join(context.prefixPath, _resolvedIndexPath)}...',
    );
    await _updateIndexFile();
  }

  @override
  bool validateRequirements() {
    // check if web config exists
    context.logger.verbose('Checking webconfig...');
    final webConfig = context.webConfig;
    if (webConfig == null || !webConfig.generate) {
      context.logger.verbose(
        'Web config is not provided or generate is false. Skipped...',
      );
      return false;
    }
    final resolvedImagePath = webConfig.imagePath ?? context.config.imagePath;
    if (resolvedImagePath == null) {
      context.logger.verbose(
        'Invalid config. Either provide web.imagePath or imagePath',
      );
      return false;
    }

    final imageFullPath = path.join(context.prefixPath, resolvedImagePath);
    if (!File(imageFullPath).existsSync()) {
      context.logger.error('image_path "$imageFullPath" does not exist.');
      return false;
    }

    // verify web platform related files and directories exists
    final entitiesToCheck = [
      path.join(context.prefixPath, _resolvedWebDir),
      path.join(context.prefixPath, _resolvedManifestPath),
      path.join(context.prefixPath, _resolvedIndexPath),
    ];

    // web platform related files must exist to continue
    final failedEntityPath = utils.areFSEntitiesExist(entitiesToCheck);
    if (failedEntityPath != null) {
      context.logger.error(
        '$failedEntityPath this file or folder is required to generate web icons',
      );
      return false;
    }

    return true;
  }

  Future<void> _generateFavicon(Image image) async {
    final size = context.webConfig?.faviconSize ?? constants.kFaviconSize;
    final favIcon = utils.createResizedImage(size, image);
    final favIconFile = await utils.createFileIfNotExist(
      path.join(context.prefixPath, _resolvedFaviconPath),
    );
    await favIconFile.writeAsBytes(
      utils.encodePngOptimized(favIcon, optimize: context.config.optimizePng),
    );
  }

  /// Emits a multi-size `favicon.ico` (16/32/48). Re-uses the same
  /// `IcoEncoder().encodeImages([...])` API the Windows writer uses
  /// (upstream #540 / #152).
  Future<void> _generateFaviconIco(Image image) async {
    final frames = [
      16,
      32,
      48,
    ].map((s) => utils.createResizedImage(s, image)).toList();
    final out = await utils.createFileIfNotExist(
      path.join(context.prefixPath, _resolvedFaviconIcoPath),
    );
    await out.writeAsBytes(IcoEncoder().encodeImages(frames));
  }

  Future<void> _generateIcons(Image image) async {
    final iconsDir = await utils.createDirIfNotExist(
      path.join(context.prefixPath, _resolvedIconsDir),
    );
    // generate icons
    for (final template in _webIconSizeTemplates) {
      final resizedImg = utils.createResizedImage(template.size, image);
      final iconFile = await utils.createFileIfNotExist(
        path.join(iconsDir.path, template.iconFile),
      );
      await iconFile.writeAsBytes(encodePng(resizedImg));
    }
  }

  Future<void> _updateManifestFile() async {
    final manifestFile = await utils.createFileIfNotExist(
      path.join(context.prefixPath, _resolvedManifestPath),
    );
    final manifestConfig =
        jsonDecode(await manifestFile.readAsString()) as Map<String, dynamic>;

    // update background_color — fall back to the top-level
    // `background_color` when `web.background_color` is unset.
    final manifestBg =
        context.webConfig?.backgroundColor ?? context.config.backgroundColor;
    if (manifestBg != null) {
      manifestConfig['background_color'] = manifestBg;
    }

    // update theme_color
    if (context.webConfig?.themeColor != null) {
      manifestConfig['theme_color'] = context.webConfig?.themeColor;
    }

    // replace existing icons to eliminate conflicts
    manifestConfig
      ..remove('icons')
      ..['icons'] = _webIconSizeTemplates
          .map<Map<String, dynamic>>((e) => e.iconManifest)
          .toList();

    await manifestFile.writeAsString(utils.prettifyJsonEncode(manifestConfig));
  }

  /// Injects (or refreshes) the PWA meta-tag block in `web/index.html`
  /// between the `<!--FLI-->` and `<!--FLIEND-->` markers.
  ///
  /// If the markers are absent the block is appended once before `</head>`
  /// when a `<head>` is present; otherwise the file is left untouched and
  /// a warning is logged so the user can paste the snippet manually.
  Future<void> _updateIndexFile() async {
    final indexPath = path.join(context.prefixPath, _resolvedIndexPath);
    final indexFile = File(indexPath);
    if (!indexFile.existsSync()) {
      context.logger.verbose(
        '$indexPath missing; skipping meta-tag injection.',
      );
      return;
    }

    final title = _resolveAppTitle();
    final statusBarStyle = context.webConfig?.themeColor != null
        ? 'black'
        : 'default';
    final block = metaTagsTemplate(title, statusBarStyle);

    var contents = indexFile.readAsStringSync();
    final markerRegex = RegExp(
      r'\s*<!--Generated by Flutter Launcher Icons-->[\s\S]*?<!--Generated by Flutter Launcher Icons--END-->',
    );
    if (markerRegex.hasMatch(contents)) {
      contents = contents.replaceFirst(markerRegex, '\n$block');
    } else {
      final headClose = RegExp(r'</head>', caseSensitive: false);
      if (!headClose.hasMatch(contents)) {
        context.logger.warn(
          '$indexPath has no <head> and no <!--FLI--> markers; '
          'add the following block manually:\n$block',
        );
        return;
      }
      contents = contents.replaceFirstMapped(
        headClose,
        (m) => '$block${m.group(0)}',
      );
    }
    indexFile.writeAsStringSync(contents);
  }

  String _resolveAppTitle() {
    // WebConfig has no title field — fall back to the project pubspec
    // `name`, which is what Flutter's default index.html uses too.
    try {
      final pubspec = File(
        path.join(context.prefixPath, constants.pubspecFilePath),
      );
      if (pubspec.existsSync()) {
        final doc = loadYaml(pubspec.readAsStringSync());
        if (doc is YamlMap && doc['name'] is String) {
          return doc['name'] as String;
        }
      }
    } catch (_) {
      // fall through to empty title
    }
    return '';
  }
}
